# Generated by Django 2.0 on 2021-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mobile_Number', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('EmailId', models.CharField(max_length=20)),
                ('AccCreated', models.DateTimeField()),
                ('FriendsList', models.CharField(max_length=20)),
                ('Private', models.BooleanField()),
            ],
        ),
    ]
