# Generated by Django 3.2.8 on 2021-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_new',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
