# Generated by Django 2.0 on 2021-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
