# Generated by Django 2.0 on 2021-10-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211018_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='AccCreated',
            new_name='Acc_created',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='EmailId',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='FriendsList',
            new_name='friendslist',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Mobile_Number',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Private',
            new_name='private',
        ),
    ]
