# Generated by Django 2.0 on 2021-10-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211018_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='user',
        ),
    ]
