# Generated by Django 3.2 on 2021-10-22 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_new_acc_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_new',
            name='acc_created',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
