# Generated by Django 2.0 on 2021-10-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211018_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Acc_created',
            new_name='acc_created',
        ),
    ]
